### ISSUE TITLE
Disconnect on AE multipart interact with ChromatiCraft

### ISSUE THREAD

**Issue by MalTeeez** [GTNewHorizons/Applied-Energistics-2-Unofficial#109]
This disconnect from dedicated server happens whenever i interact with ae2 multiparts(cables, terminals, ..) [gist](https://gist.github.com/MalTeeez/e8e393d59e5774bab6373f600130546f).
Posting this here since it doesn't happen with the last official 1.7 version of ae2, prob related to this [commit](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/439ae2e563d174995acbe0d630f9e2b973103205)

**Comment by draknyte1** [comment]
Blame Reika and DragonAPI.

**Comment by boubou19** [comment]
AE2 is heavily modified in comparison to the last official AE2 build for 1.7. As said by Alk, DragonAPI and Reika are also heavily modifying the environment in which they are loaded, so no wonder why it's causing issues.
