### ISSUE TITLE
New Interface Function

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/Applied-Energistics-2-Unofficial#117]
Add Another Blocking mode that wont ignore integrated circuits, usefull for Automated LCR

**Comment by repo-alt** [comment]
How can that be useful? If you need the circuit for the recipe then it should be ignored, and if you don't, then why did you put it there?

**Comment by LewisSaber** [comment]
for autocrafting in chemical reactor i put circuits and i dont want to put another recipe if there is circuit alreay

**Comment by repo-alt** [comment]
You include the circuit in the pattern? How do you remove it from the input bus?

**Comment by LewisSaber** [comment]
I remove it with item conduit that is connected to it with transvector

**Comment by repo-alt** [comment]
Well, you can easily work around the issue by adding some dummy item to the end of the recipe, like cobble block, but the request is legit (although very niche).

**Comment by MCTBL** [comment]
seems is already fixed?

**Comment by serenibyss** [comment]
Added in #308
