### ISSUE TITLE
<Suggestion> Increase in fluid types on the storage drives

### ISSUE THREAD

**Issue by anoldshoe** [GTNewHorizons/Applied-Energistics-2-Unofficial#128]
I felt it never made sense that with all the hundreds of fluid types in the modpack, why we only have up to 5 types per drive. Essentia drives, as an example, has 12 types of essentia per drive, and there are only 67 different essentia.

I would recommend a minimum of 12 types for fluid per drive.

**Comment by boubou19** [comment]
ExtraCells2 is incredibly bugged, prone to dupe bugs. We want to remove the fluid part from the pack. So i'm afraid it will not happen.

**Comment by anoldshoe** [comment]
> ExtraCells2 is incredibly bugged, prone to dupe bugs. We want to remove the fluid part from the pack. So i'm afraid it will not happen.

Ah! Thanks for that quick response.
