### ISSUE TITLE
No ME controller animation

### ISSUE THREAD

**Issue by Petrol12** [GTNewHorizons/Applied-Energistics-2-Unofficial#133]
Hello, I don't have ME controller animation. The original does not have this problem. All controllers are the same color, do not flash

**Comment by boubou19** [comment]
whoopsie, i though it was NH repo mybad

**Comment by LewisSaber** [comment]
maybe you have this optifine setting off?
![image](https://user-images.githubusercontent.com/39595617/162238000-60bbfbdc-1f96-4a7c-8883-75eadb7f3a17.png)

**Comment by repo-alt** [comment]
Closing as stale
