### ISSUE TITLE
the oredictionary filter works mistakenly

### ISSUE THREAD

**Issue by RUEEE** [GTNewHorizons/Applied-Energistics-2-Unofficial#137]
if more than one symbol ( & , | ) is written in one oredictionary filter and the first conjunction is "|", the filter will process all symbols as "|".
e.g. use string "ore*|dustImpure*|dustPure*&!crushedPurifiedGalena&!crushedPurifiedGalena" for the oredictionary upgrade in ME export bus will cause all items export wrongly...

**in util/prioitylist/oreFilteredList , line 82**
the varible "lastFilter" will never update after inited as the first filter, which results in all the symbols except the first one and other "|" is ignored

**Comment by repo-alt** [comment]
that is probably fixed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/138
