### ISSUE TITLE
[outside-pack issue] Chromaticraft crash on AE2 cable event 

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/Applied-Energistics-2-Unofficial#152]
This may need to be renamed appropriately; (sorry for the bracket thing if it bothers you, more of a force of habit)

the bug here is caused when a cable receives a network update or whatever it may be when you're looking at it when chromaticraft is present. This issue can be avoided as long as you do not place the network blocks and stuff on the cable itself, otherwise, it will cause an arrayOutOfBounds error.

this issue is seen to be only occurring in GTNH instances and has happened to me in the last public update released on curse (the one with the false positive antivirus response; Ver 2.1.2.3)

this was reproduced in a lite pack and should by the looks of being reproducible in an isolates pack with just the necessities for both mods to function

(Tip: if the pack crashes, be aware that it will do that once and then proceed like normal, it does this whenever a change in the mods occurs)
(tip II: Dragon API is required, otherwise the pack will crash on boot; covering this just in case, you never really know)

this issue has been reported by another individual and I happen to have the same issue, the link to this can be found here and by the looks Reika is needing more info on the issue to patch it

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/2977

**Comment by SteamDoge9000** [comment]
crash log: (forgot to upload that XD)
[crash-2022-07-10_02.38.37-server.txt](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/9078820/crash-2022-07-10_02.38.37-server.txt)

**Comment by repo-alt** [comment]
Thanks for the callstack, the reason of the crash doesn't seem to be at our side (although probably caused by our changes). I try to keep the API unchanged but Reika is probably using some implementation details, judging by the call stack. Should be easy to fix on his side I think.
