### ISSUE TITLE
SiliconPrint method lost

### ISSUE THREAD

**Issue by wuyaiii** [GTNewHorizons/Applied-Energistics-2-Unofficial#178]
appliedenergistics2-1.7.10-rv3-beta-104-GTNH.jar
SiliconPrint method lost
I don't know if it's normal
But my players need this so I added in the crafting table

If anyone needs this production method please create a new file circuits.recipe in materials folder
[.minecraft\config\AppliedEnergistics2\recipes\user\materials\circuits.recipe]
inscribe=
    oredictionary:ingotGold ae2:ItemMaterial.LogicProcessorPress
    -> ae2:ItemMaterial.LogicProcessorPrint

inscribe=
    ae2:ItemMaterial.PurifiedCertusQuartzCrystal ae2:ItemMaterial.CalcProcessorPress
    -> ae2:ItemMaterial.CalcProcessorPrint

inscribe=
    oredictionary:gemDiamond ae2:ItemMaterial.EngProcessorPress
    -> ae2:ItemMaterial.EngProcessorPrint

inscribe=
    oredictionary:itemSilicon ae2:ItemMaterial.SiliconPress
    -> ae2:ItemMaterial.SiliconPrint

**Comment by GTNHAfx237v7** [comment]
Wasn’t it changed from raw silicon to solar grade silicon? Maybe a bad idea to update ae2 only?

**Comment by wuyaiii** [comment]
> Wasn’t it changed from raw silicon to solar grade silicon? Maybe a bad idea to update ae2 only?
![image](https://user-images.githubusercontent.com/50183639/191256029-128a8b7a-3745-47a1-be45-311d0aac0113.png)
I'm missing silicon plate synthesis here instead of silicon

**Comment by quentin452** [comment]
i have this issue too

**Comment by quentin452** [comment]
use appliedenergistics2-1.7.10-rv3-beta-102-GTNH

**Comment by Dream-Master** [comment]
looks fine to me. 
![image](https://user-images.githubusercontent.com/2970688/191363496-41541819-6653-41f3-8712-7baaa3d81c46.png)

**Comment by Dream-Master** [comment]
not sure it was fixed in 2.2.0.0-RC-3 but after this definitely.

**Comment by Dream-Master** [comment]
outside GTNH idk

**Comment by Serega007RU** [comment]
PR #174 is to blame for this problem
