### ISSUE TITLE
The handheld terminal can open other players' terminals to take items

### ISSUE THREAD

**Issue by wuyaiii** [GTNewHorizons/Applied-Energistics-2-Unofficial#203]
Forge version：1.7.10-Forge10.13.4.1614-1.7.10
AE2 version：appliedenergistics2-1.7.10-rv3-beta-122-GTNH
Server or Single Player：Server
This bug existed a long time ago

When a player holds a panel such as a crafting terminal, interface terminal, fluid terminal or luminous panel, and Then right click on someone else's terminal where ME Security Terminal is not placed, such as a crafting terminal, interface terminal, to steal the items inside,take things without the permission of the  island[plugin-ASkyBlock] or plots [plugin-plotsquared] 

It may be that [plugin-ASkyBlock] and [plugin-plotsquared] are not perfect. These two plug-ins can indeed block thieves from holding other items to open other players’ terminals, but they cannot block the handheld terminal from opening the terminal
so if this issue is incorrect, you can Close directly, thank you very much

**Comment by repo-alt** [comment]
Well, it is probably correct just not about AE2 I'm afraid.

**Comment by Connor-Colenso** [comment]
Beyond the scope of GTNH, this is a plugin specific issue.
