### ISSUE TITLE
Bug with AE and ae2fs.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/Applied-Energistics-2-Unofficial#229]
Error render ME Dual Interface.
![изображение](https://user-images.githubusercontent.com/9840821/213280778-675f942e-29a3-4015-bc11-720e288c842b.png)
Latest modpack 2.2.8
Update only two mods from git :
appliedenergistics2-1.7.10-rv3-beta-142-GTNH
ae2fc-1.7.10-1.0.54-gtnh-pre

**Comment by Dream-Master** [comment]
you need to update more mods than this. Please wait for a new version 2.2.9

**Comment by Pilad** [comment]
> you need to update more mods than this. Please wait for a new version 2.2.9

This is exactly the problem in the ae2fs mod, the flat dual interface has disappeared.

**Comment by Pilad** [comment]
> @Pilad but you just use 2.2.8 and update only this two mods right?

Yes.

**Comment by Pilad** [comment]
![изображение](https://user-images.githubusercontent.com/9840821/213286643-be3149c6-f6d2-4026-b584-8587689ec380.png)

**Comment by Dream-Master** [comment]
@Pilad can you check with this version ? if ae and aefc mod not updated add it yourself
https://cdn.discordapp.com/attachments/603348502637969419/1064245631494934628/GTNH-test-2.2.9-3-dev-pre.zip

will upload a 2.2.9-4 test version later or tomorrow

**Comment by Pilad** [comment]
> 

Ok. Download.

**Comment by Pilad** [comment]
> @Pilad can you check with this version ? if ae and aefc mod not updated add it yourself https://cdn.discordapp.com/attachments/603348502637969419/1064245631494934628/GTNH-test-2.2.9-3-dev-pre.zip
> 
> will upload a 2.2.9-4 test version later or tomorrow

Work
![изображение](https://user-images.githubusercontent.com/9840821/213291424-2d3aa01b-ce41-472d-bd28-54a304e6acfe.png)

**Comment by Pilad** [comment]
Storage Bus and level emitter missing in this version.

**Comment by Dream-Master** [comment]
@Pilad see thats what i mean you cant only update a few mods with a old version :)
It would be very nice to ask me for a new version in the future because some mads had new dependencies to other mods that was not updated in our case i guess.

**Comment by Dream-Master** [comment]
<https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/64>
guess it is in this pr ?

**Comment by Pilad** [comment]
> @Pilad see thats what i mean you cant only update a few mods with a old version :) It would be very nice to ask me for a new version in the future because some mads had new dependencies to other mods that was not updated in our case i guess.

ae2fs depends only on AE

**Comment by Dream-Master** [comment]
and this <https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/62>

**Comment by Pilad** [comment]
> > > @Pilad see thats what i mean you cant only update a few mods with a old version :) It would be very nice to ask me for a new version in the future because some mads had new dependencies to other mods that was not updated in our case i guess.
> > 
> > 
> > ae2fs depends only on AE
> 
> Nope https://github.com/GTNewHorizons/AE2FluidCraft-Rework/blob/master/dependencies.gradle

You version ae2fs is old
![изображение](https://user-images.githubusercontent.com/9840821/213292376-77c22309-a1e6-4848-b821-ab2971f89b78.png)

**Comment by Dream-Master** [comment]
then we need to upgrade this file as well

**Comment by Pilad** [comment]
> 

If update ae2fs from 51 to 54: Work
After update AE from 139 to 142 : not work
The same error appears. AE version problem
![изображение](https://user-images.githubusercontent.com/9840821/213295406-c3ba860d-6739-46d4-a461-460670fc1057.png)

**Comment by Pilad** [comment]
> then we need to upgrade this file as well

Problem in 142 version of AE

**Comment by Dream-Master** [comment]
@Pilad did you compile it with newest version

**Comment by Pilad** [comment]
> @Pilad did you compile it with newest version

In the latest version of AE on the git, they only cut out the check for updating the mod. Mod actually assembled 142 versions the most current

**Comment by Dream-Master** [comment]
i am confused. Did the pack 2.2.9-3 loads with ae 142 and aefc 54 flawless or not ?

**Comment by Pilad** [comment]
> i am confused. Did the pack 2.2.9-3 loads with ae 142 and aefc 54 flawless or not ?

Modpack 2.2.9-3 starts with ae 142 and aefs 54 but has the same error as I showed above. There is no flat interface and there is spamming in the console. No crafting flat me interface.

**Comment by Pilad** [comment]
> i am confused. Did the pack 2.2.9-3 loads with ae 142 and aefc 54 flawless or not ?

This PR breaks mod AE https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/7b1ac385feb40e41257c0e3d2ef5fca7aa30ed36
