### ISSUE TITLE
Flat fluid interface bug.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/Applied-Energistics-2-Unofficial#235]
Update mods. Latest modpack.
ae2fc-1.7.10-1.0.58-gtnh
appliedenergistics2-1.7.10-rv3-beta-149-GTNH

We check on any craft. For example, liquid rubber in plates.
![изображение](https://user-images.githubusercontent.com/9840821/214375451-f115922e-95c2-443e-a5da-8ebb60400882.png)
The recipe is in the terminal.
![изображение](https://user-images.githubusercontent.com/9840821/214375631-d5bb6202-d892-4392-b7be-db8464e5126e.png)
Now let's go to the main menu of the game and go back to the world. And the plate recipe is gone.
![изображение](https://user-images.githubusercontent.com/9840821/214375919-e20d1538-7e1d-465b-849b-8bf99b7ee7d1.png)
If you pull out the template with the plate from the fluid interface and place it back, the plate recipe will appear in the terminal.
It was also noticed that if the interface is flat and full-sized, then the recipes do not disappear.
The full-sized interface also does not lose plate recipes when re-entering the world, and they are displayed in the terminal.

**Comment by Pilad** [comment]
flat+full-size (only full-size) work fine
![изображение](https://user-images.githubusercontent.com/9840821/214376833-3439ff06-9b59-40d6-bbb0-be035b5df12e.png)
![изображение](https://user-images.githubusercontent.com/9840821/214376895-54298b6f-6dbb-477c-baf0-765e24b52b8b.png)
Re-enter
![изображение](https://user-images.githubusercontent.com/9840821/214377021-63319d7c-d9f4-4807-976e-699f63704798.png)

**Comment by Pilad** [comment]
Only full-size interface work fine.
![изображение](https://user-images.githubusercontent.com/9840821/214377706-ba51ef99-abda-49f4-9f71-8b477ef4cb40.png)
![изображение](https://user-images.githubusercontent.com/9840821/214377735-8cba0a9d-dc8b-4d51-8e4d-d28b1d18c692.png)
![изображение](https://user-images.githubusercontent.com/9840821/214377816-a8898731-ec11-482b-9016-1e751ca601bb.png)

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/e424230f96e0a2b4697f1996588a3efef7cb785b
