### ISSUE TITLE
Compatibility with AppliedExchange mod

### ISSUE THREAD

**Issue by ORanGeOfficial** [GTNewHorizons/Applied-Energistics-2-Unofficial#247]
I'm getting `Connection Lost` error every time I open AE2 terminal with AppliedExchange and ProjectE mods installed (single player with no other mods). It throws me to the server selection screen without client crash. Official AE2 version works fine with AppliedExchange.

[Full log link](https://pastebin.com/E85R0buZ) 

**AE2 version:** GTNH rv3-beta-159
**AppliedExchange version:** 1.7.10-0.1.2
**ProjectE version:** 1.7.10-PE1.10.1

AppliedExchange curseforge page says that renaming AE2 jar file will cause the crash if you open any sortable AE2 Inventory. I tried renaming the AE2 jar, but no luck. This solution only works for the official AE2 version.

**Comment by jrslwium** [comment]
i have crash with ae2 additions since September 2022
They still don't fix it
might not fix your
but you can try Equivalent Energistics

**Comment by mitchej123** [comment]
This looks like a reflection/ASM issue with the mods you're using. We don't break compatibility on purpose, but we also don't  go out of our way to ensure it works outside the pack.  

We'd accept a PR to fix it (or likely it needs to be adjusted upstream), but I don't believe anyone here uses project E nor would be interested in fixing this.l


```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_302]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_302]
	at appeng.core.sync.GuiBridge.ConstructGui(GuiBridge.java:415) ~[GuiBridge.class:?]
	... 39 more
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    appeng/client/me/ItemRepo.updateView()V @798: aload
  Reason:
    Type top (current frame, locals[8]) is not assignable to reference type
  Current Frame:
    bci: @798
    flags: { }
    locals: { 'appeng/client/me/ItemRepo', 'java/lang/Enum', 'java/lang/Enum', 'appeng/client/me/ItemRepo$SearchMode', 'java/util/regex/Pattern', integer, 'java/lang/Enum', 'java/lang/Enum' }
    stack: { }
```
