### ISSUE TITLE
AE2 does not display tier or duration of thermal expansion potions in the network

### ISSUE THREAD

**Issue by magicmq** [GTNewHorizons/Applied-Energistics-2-Unofficial#294]
Thermal foundation allows for management of potions as fluids and also adds several additional tiers/durations of potions. I am importing several of these potions into the ME network (for example, potion of leaping, which includes jump boost I, jump boost II, jump boost extended duration, etc.). When I import several different tiers/durations of potions into the network, this is all I see in a fluid terminal for each type of potion:
![80FHP7A](https://user-images.githubusercontent.com/5727635/228105195-87a7e7af-d678-4e16-82a9-5d7306568d15.png)
I have several different tiers/durations of "potion of leaping" in the ME network, but all I see is "potion of leaping" for all. This makes it impossible for me to differentiate between tiers/durations when I am working with these fluids and filling devices/containers.

Additionally, I noticed this same issue was reported in 2018 on the official Applied Energistics 2 repository: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3790/. The issue has been marked as completed, but it doesn't appear to have been fully fixed.

AE2 knows that these fluids are different on the back end because they are stored as separate fluids in the ME network, and the NBT data for each of these differs. That being said, I would like AE2 to reflect the precise difference between these potions on the front end as well, ideally by displaying the tier and duration of the potion (in addition to its name) in the fluid terminal and in any other relevant locations.

**Comment by firenoo** [comment]
Wouldn't this be an Extra Cells 2 or AE2FC issue? AE2 doesn't have fluid terminals.
