### ISSUE TITLE
Bug with displaying non-stackable items

### ISSUE THREAD

**Issue by Goodbird-git** [GTNewHorizons/Applied-Energistics-2-Unofficial#296]
There is a bug with displaying non-stackable items with different NBT-tags in ME grid. If I use a storage bus with a regular chest and put there two diamond swords, one with sharpness 1 and one with sharpness 2, it will show that I have only one sword, the one with sharpness two.  It works with other non-stackables with different NBT-tags, such as forestry backpacks and others
![image](https://user-images.githubusercontent.com/80464896/231076434-4101fa26-580f-4a09-80e5-20e7be6003e7.png)
![image](https://user-images.githubusercontent.com/80464896/231076044-5b0449a1-5221-4c09-b374-bc0717b3ff64.png)
![image](https://user-images.githubusercontent.com/80464896/231076082-301e04b0-0338-430f-974a-374b370c1cf9.png)
![image](https://user-images.githubusercontent.com/80464896/231076184-7289a2cc-2bc2-427f-a7a5-0c931aa012d3.png)
![image](https://user-images.githubusercontent.com/80464896/231076235-76229071-4dfd-4543-a07f-92e1ff9fe400.png)

**Comment by firenoo** [comment]
AE2 version?

**Comment by Goodbird-git** [comment]
AE2 version is  appliedenergistics2-rv3-beta-191-GTNH-pre

**Comment by firenoo** [comment]
Use beta-190 or beta-192-pre, 191-pre had an optimization feature that is discontinued

**Comment by Goodbird-git** [comment]
Thank you!
