### ISSUE TITLE
Cannot find meteorite with the meteorite compass even if i use a fresh instance

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Applied-Energistics-2-Unofficial#301]
mods list : 
appliedenergistics2-rv3-beta-195-GTNH

description : 

the compass spins infinitly ,does somethings get changed in AE2 to find meteorite?

![Capture d’écran_2023-04-17_11-28-36](https://user-images.githubusercontent.com/42176772/232443979-744e7dd9-3d00-4437-bdd5-08c00b6be246.png)

**Comment by quentin452** [comment]
so the issue appear since this release

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-119-GTNH-pre

**Comment by repo-alt** [comment]
Meteors are now much more rare, one meteor is generated in a 707x707 square by default (configurable). Compass only works when a meteorite is actually generated, and the distance to it is less than 174 (hardcoded)
