### ISSUE TITLE
[server lag]The server runs for a period of time and experiences a lag problem

### ISSUE THREAD

**Issue by mcmso** [GTNewHorizons/Applied-Energistics-2-Unofficial#317]
version:
GTNH:2.3.0R
EnderIO-2.4.15-pre
appliedenergistics2-rv3-beta-190-GTNH
ae2stuff-0.5.1.16-GTNH
ae2fc-1.0.92-gtnh

The server runs for a period of time and experiences a lag problem
![E@16EGF3_K4ZP9F4 Z$HGOE](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/46519955/c09a0edc-daf0-4295-b222-d58f145da034)
If you need additional information, please contact me and I will provide it promptly

**Comment by repo-alt** [comment]
Can you unwrap EnergyGridCache.onUpdateTick? Also what is used as a power source?

**Comment by mcmso** [comment]
> Can you unwrap EnergyGridCache.onUpdateTick? Also what is used as a power source?

![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/46519955/696d9f87-b418-48b6-8c8b-13fe25750470)

**Comment by mcmso** [comment]
> ok, and the second question?

![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/46519955/8822f8d1-e26d-4f0c-836e-0a4d644b2b7a)

**Comment by mcmso** [comment]
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/46519955/96eb7ff1-ae8f-42f8-b6f8-bbed1c37adfc)

**Comment by repo-alt** [comment]
using ic2 energy grid is not exactly a good idea

**Comment by repo-alt** [comment]
Also maybe add some dense energy cells to the AE2 as a buffer

**Comment by mcmso** [comment]
> ok, and the second question?

I used the rec's generator to generate electricity for ElectriCraft, which was then connected to the wires of the eu converter to gt
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/46519955/ff4fada9-d701-4d52-afd1-6b584e7e8a74)

**Comment by mcmso** [comment]
> EnergyGridCache

Does this mean I'm using energy incorrectly, causing the EnergyGridCache to lag?

**Comment by repo-alt** [comment]
I'm not sure what energy grid reactorcraft is using, never saw that mod. 
Another possible issue if we leave off the energy is chunkloading - 5% time for PathGridCache suggests that some parts of the grid are getting connected/dsconnected. Make sure that all of the base with AE networks is loaded (or unloaded) a a whole.

**Comment by mcmso** [comment]
> I'm not sure what energy grid reactorcraft is using, never saw that mod. Another possible issue if we leave off the energy is chunkloading - 5% time for PathGridCache suggests that some parts of the grid are getting connected/dsconnected. Make sure that all of the base with AE networks is loaded (or unloaded) a a whole.

I will continue to try to solve this problem. Thank you for your help

**Comment by szuend** [comment]
Is this still a problem? There was an attempt with #371 to improve the performance of the energy grid.
