### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vasmark1** [GTNewHorizons/Applied-Energistics-2-Unofficial#345]
```
Installation
You install this mod by putting it into the minecraft/mods/ folder. It has no additional hard dependencies.
```
This mod can run without all GTNH core mods or it's a mistake in description? Thanks for great work!

**Comment by wlhlm** [comment]
This is meant to be usable outside of GTNH. If it doesn't work, then that's a bug. Please refer to our mod support spreadsheet: https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/edit#gid=1469028684
