### ISSUE TITLE
[BugReport]About EnergyCell's getCapacity method

### ISSUE THREAD

**Issue by HiddenCirno** [GTNewHorizons/Applied-Energistics-2-Unofficial#347]
In class AEBaseItemBlockChargeable there is a method named getMaxEnergyCapacity to get energy cell's capacity, but this method is just have 2 return——if your cell is normal cell, return 20k capacity, or your cell is not normal cell, it's will return 160k capacity and it's dense cell's capacity, it's mean if there is a bigger cell in plan or someone make a new cell. it's will still return dense cell's capacity....

**Comment by firenoo** [comment]
Since there are no plans to add a larger energy cell I would not consider this a bug.
