### ISSUE TITLE
[Feature request] In-place doubling of patterns

### ISSUE THREAD

**Issue by Sopel97** [GTNewHorizons/Applied-Energistics-2-Unofficial#355]
It's annoying that it's necessary to take a pattern out of one terminal, put it in the other terminal, double it, and put it back in the first terminal. It should be feasible to add a hotkey to double patterns. Currently it's coupled with the pattern terminal, but I see no reason why it should be 

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/fec3a4544b6a98d13978454320256da59dec9a9b/src/main/java/appeng/container/implementations/ContainerPatternTerm.java#L582

and

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/fec3a4544b6a98d13978454320256da59dec9a9b/src/main/java/appeng/container/implementations/ContainerPatternTermEx.java#L407C22-L407C22

could be consolidated too

**Comment by firenoo** [comment]
The reason we haven't merged the two is because of NEE.

**Comment by firenoo** [comment]
To be honest I didn't read it through too clearly but now that I read it clearly I think what you really want is a pattern + interface terminal combo

**Comment by Sopel97** [comment]
Why the need for such complications, I just want to double the pattern without moving it.

**Comment by serenibyss** [comment]
Resolved in #362
