### ISSUE TITLE
"Highlight interface" works with errors if shader on

### ISSUE THREAD

**Issue by kirilwapj** [GTNewHorizons/Applied-Energistics-2-Unofficial#358]
When the shaders are enabled, the "Highlight interface" works every once in a while, sometimes it works, sometimes it doesn't, sometimes it can disappear when moving. 

Tested on
appliedenergistics2-rv3-beta-232-GTNH-stable-patch-backport.jar
And
appliedenergistics2-rv3-beta-225-GTNH.jar

optifine_1.7.10_hd_u_e7

lwjgl3 and lwjgl2

with and without fastcraft

Shaders that were used:
Sildur's+Vibrant+Shaders+v1.50+Extreme-VL

Sildur's+Enhanced+Default+v1.15+Fancy

ComplementaryShaders_v4.7.2

Chocapic13_V9.1_Extreme_beta_5

Chocapic13 V6 Lite

BSL_v8.0

potatofasteranwonderfull178154551

The problem was the same for all configurations.

How to fix this problem and what is causing it?

**Comment by serenibyss** [comment]
Optifine shaders are no longer supported

**Comment by kirilwapj** [comment]
Thx for request, this fixed in last angelica
