### ISSUE TITLE
Crash when a dense cable (or smart dense) is placed behind a P2P tunnel

### ISSUE THREAD

**Issue by ThiagoSolfo** [GTNewHorizons/Applied-Energistics-2-Unofficial#382]
# The bug
- A crash happens when a dense cable (or smart dense) is placed behind a P2P tunnel (whatever P2P - RF, ME, etc)
- Crash: https://paste.gg/p/anonymous/4e9230051cdd4862aaf1d87267992c58

# Expected behavior
- Unable to place the cable or placed a block behind

# Actual behavior
- Crash

# Steps
1. Place a P2P tunnel
2. Click behind the P2P tunnel with a dense cable
3. Crash

# Screenshots

> Showing the P2P tunnel
![2023-09-03_13 56 57](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/61445366/8e5d8383-2893-4f65-9ceb-e215290239db)

> Trying to place the dense cable behind the tunnel
![2023-09-03_13 57 19](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/61445366/f79d4715-daba-4563-8621-b40e0659702f)

> And then, crash
![dllhost_gUEzTaZH1I](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/61445366/cc3699c7-2eb3-466c-82b4-c2c2d2049c70)

# Files
- appliedenergistics2-rv3-beta-249-GTNH
- forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by querns** [comment]
java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench

Try with buildcraft.

**Comment by ThiagoSolfo** [comment]
> java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
> 
> Try with buildcraft.

The error does not happen with buildcraft (buildcraft-7.1.25)
So for the crash not to occur it is mandatory to have it installed apparently
