### ISSUE TITLE
Thermal Expansion Crescent Hammer no longer removes cables/machines

### ISSUE THREAD

**Issue by Midnight145** [GTNewHorizons/Applied-Energistics-2-Unofficial#395]
Unsure if this was intended or not, as Thermal Expansion is not in GTNH, but thermal's wrench will no longer remove cables like the yeta wrench/certus quartz wrench. It will still rotate blocks like the interface, allowing you to point it at a specific block, you just can't shift+rightclick to pick up a cable.

AE2 Version: appliedenergistics2-rv3-beta-258-GTNH

**Comment by firenoo** [comment]
as a preliminary triage, do you have BC installed?

**Comment by Midnight145** [comment]
I do not, it's running in Blightfall which doesn't include BC.

**Comment by firenoo** [comment]
Alright, I've pinned down the bug (I think). Seems like we went a bit too far in trying to remove BC as a hard dependency.
