### ISSUE TITLE
game crashing with chromaticraft

### ISSUE THREAD

**Issue by bessonowjaroslaw** [GTNewHorizons/Applied-Energistics-2-Unofficial#409]
[latest.log](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/13040010/latest.log)
[crash-2023-10-19_13.36.07-client.txt](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/13040012/crash-2023-10-19_13.36.07-client.txt)

**Comment by miozune** [comment]
This looks unrelated to AE2, report to Reika
