### ISSUE TITLE
Show used/free interface slots in tooltip

### ISSUE THREAD

**Issue by AnrDaemon** [GTNewHorizons/Applied-Energistics-2-Unofficial#412]
I don't know if this is better suited to AE2 itself, or WAILA/WAWLA, but it would be extra useful to be able to see interface patterns' slots usage in the tooltip before opening the interface UI. Especially important when looking for a free slot between crafting CPU's molecular assemblers.

**Comment by joshaup1999** [comment]
Or you could just open the interface terminal

**Comment by AnrDaemon** [comment]
Which one?

![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/6532485/c59c50aa-b976-4108-a756-855a5559fc48)

**Comment by joshaup1999** [comment]
There’s a terminal called the interface terminal. It shows you all your interfaces on the network

**Comment by AnrDaemon** [comment]
Did't know you could set terminals like that. Sorry.
