### ISSUE TITLE
a bug in 286

### ISSUE THREAD

**Issue by ThickBlueberryJuice** [GTNewHorizons/Applied-Energistics-2-Unofficial#429]
There is maybe a bug we found. When we use the AE network for a synthesis task with the fluid output as the result, the fluid has returned to the network, but the CPU does not recognize it and still shows that the synthesis is in progress.

**Comment by Tomekosi** [comment]
+1, me and my friend updated to nightly gtnh-nightly-2023-11-19+227-mmcprism-new-java, same bug, sometimes (very rarely) the fluid would register as crafted, but around 99% of the time it would not. However when a fluid is just an ingredient it will go smoothly.

Let me start by saying, that what I will write below may be 100% incorrect, and this is just a hunch.
I tried to review the AE code for crafting(as far as i can), and the only thing that would make sense is the following commit:
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/392/commits/a31f0541efb7565b0bbd25bca490882148ef8846

I suspect that maybe something was not imported?

**Comment by RhyVis** [comment]
I got similar bug as I tried to update ae from 281 to 282 separately, not sure what caused this

**Comment by Dream-Master** [comment]
did 287 works ? @q2413274903 @Tomekosi @RhyVis

**Comment by q2413274903** [comment]
In fact, not long ago, I tried the formula of fluid extraction of molten tin in 287. Unfortunately, this bug still exists.
On the other hand, a friend of mine said that he had tried three versions of 285.286.287, and the result was that this bug existed in all three versions. Another friend of mine said that he also had this bug in the 282 version, but he didn't have this bug after returning the version to 281.Maybe the problem appears in the update of 282? @Dream-Master

**Comment by RhyVis** [comment]
> did 287 works ? @q2413274903 @Tomekosi @RhyVis

Sadly I still caught this bug when testing with nightly-build 2023-11-21(with 287 in it), the fluids always have some left as "crafting" even if all the fluids have returned to the ae network.

I tested with molten iron extracting recipe with one iron block
The leftover:
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/65334131/a67e843c-1a96-40bb-8db7-279978512c09)

The fluids already returned to network:
![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/65334131/9952548a-6fa6-4db8-82dd-9ba84fc0cf5d)

**Comment by q2413274903** [comment]
I tested some other recipes in version 287, and the end result was that if the product had a fluid in it, the fluid synthesis would not be recognized by the CPU, but if the fluid was a transit product and the final product had no fluid, the synthesis task would be successfully completed and recognized by the AE network.

**Comment by Congyulinplus** [comment]
@Phineasor @tth05 The problem only appeared after version 282 was released, suspecting it was related to phineasor and the pr version released by tth05.

**Comment by Dream-Master** [comment]
@tth05

**Comment by MCTBL** [comment]
Should fixed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/434
