### ISSUE TITLE
Feature request: RefinedStorage "holding shift makes items in terminal not move" feature

### ISSUE THREAD

**Issue by TheUnderTaker11** [GTNewHorizons/Applied-Energistics-2-Unofficial#442]
As title says. That's one of the biggest features I miss when using AE over refined.

When holding shift, nothing in the terminal you are viewing should shift around (even if an item goes to 0, it still displays there as 0 until you let go of shift.)

**Comment by TheUnderTaker11** [comment]
Hey I noticed when I upgraded to latest AE2 version the shift feature has been reverted, please re-open this issue as it is a very nice QOL to have in the terminal.

**Comment by boubou19** [comment]
it caused too much issues, so it has been reverted

**Comment by TheUnderTaker11** [comment]
Yea I saw that, I assume that's just an implementation issue though and the feature isn't impossible?
