### ISSUE TITLE
No recipes when swapped into existing modpack

### ISSUE THREAD

**Issue by vishtheshnu** [GTNewHorizons/Applied-Energistics-2-Unofficial#459]
When I replaced the AE2 version in the Minecraft Millionaire modpack with version `rv3-beta-316-GTNH`, NEI (the original version, not the GTNH version) shows no recipes for any AE2 block or item except for the ones added through crafttweaker. Switching back to the original version of AE2 (rv3-beta-6) fixes this and all recipes appear again.

I used the latest versions available for each of these, including `Minecraft Millionaire-2.1`

**Comment by Pilzinsel64** [comment]
I took a look as I ran into the same issue just now. This PR seems to be the cause: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/453

Giving a test via #460 Let you know more later.

**Comment by Pilzinsel64** [comment]
Try beta 319 (build should finish in few minutes).

**Comment by Pilzinsel64** [comment]
There seems to be another issue where the recipes absolutely don't want to load. My PR fixed that for exactly one startup.
But sadly I have not time to investigate these days. Maybe someone else want to pick that up.
