### ISSUE TITLE
ae2 processor list ui

### ISSUE THREAD

**Issue by Rutikk** [GTNewHorizons/Applied-Energistics-2-Unofficial#472]
Is there any way to make processor panel list ui scaleble / bigger ? Its a bit inconsistant with latest crafting status ui change
![ae2old](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/38359602/848e3f9f-0c57-4700-bfef-8b7847416086)

**Comment by MCTBL** [comment]
| short | tall |
| :-: |  :-: |
| ![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/d5c81c40-52ab-4d84-8f6a-3df52e3130b3) | ![image](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/118d88ee-975f-4ae2-a929-83d9e9fd08f2) |
