### ISSUE TITLE
Interface terminal crashes after multiple clicks

### ISSUE THREAD

**Issue by AnLi9527** [GTNewHorizons/Applied-Energistics-2-Unofficial#520]
Interface terminal，Crash due to continuous clicking while dragging the template.
Click on the following location.
![1](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/108027962/631fb703-92f3-4979-99e5-2f66ebd37115)
![2](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/108027962/db966e09-a6ae-4c60-9145-31c95e96d895)

latest log:
https://pastebin.com/cvTa8MAu

**Comment by serenibyss** [comment]
This has been fixed in newer versions of the mod
