### ISSUE TITLE
ae2 "merge craftings" dupe bug

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/Applied-Energistics-2-Unofficial#538]
### Your GTNH Discord Username

tom6482

### Your Pack Version

nightly 568

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

stuff to work

### The Reality

if you merge a order with ae2, materials will be added to the cpu without being subtracted from anywhere

### Your Proposal

have the merge functionality use the materials it adds to the cpu

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
related pr: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/523
@pashabou so you are aware

**Comment by Caedis** [comment]
Able to recreate in a test world

**Comment by Caedis** [comment]
That fixed it, thanks

**Comment by tommmmmmmmm** [comment]
the bug seems to persist in build 569, is it me or what?

**Comment by pashabou** [comment]
Nightly 569 is using AE2 version "rv3-beta-416-GTNH-pre", which is 3 days old. I don't know when a new prerelease version of AE2 including the latest commit will be published, but probably within the next few days.
