### ISSUE TITLE
Multiplayer Bug

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/Applied-Energistics-2-Unofficial#577]
After a long time I decided to update my version from 410 to the latest version available, 453, however I realized that when a craft is requested on the server the next button does not work, but in singlerplayer this button works, with this in mind I tested the other versions to trying to find where this problem started, I found the problem starting in version 412, that is, there was some change in the way the craft request works from version 410-411 to version 412, thus making it only possible to advance to the screen craft if you are in single player, on the server the button does not send the information to advance to the craft confirmation screen.

Multiplayer button does not work
![image](https://github.com/user-attachments/assets/43f331e4-f543-4392-b777-35ccbe64b848)

SinglerPlayer button works fine
![image](https://github.com/user-attachments/assets/3d5561df-4854-4b90-9297-d903d7abeda9)

**Comment by SrYthan** [comment]
Maybe I found the problem, it turns out that I use Crucible for my server, and the problem apparently lies with it, because when downloading Thermos to test it worked correctly to advance the craft plan page, therefore, what was changed from version 411 for the 412 that caused such incompatibility with the crucible?

**Comment by EverNife** [comment]
It seems to be caused by a Crucible's fastutil not being updated.
It was fixed at Crucible.

**Comment by serenibyss** [comment]
Resolved according to most recent comment
