### ISSUE TITLE
something wrong makes bugs with NPE

### ISSUE THREAD

**Issue by ThickBlueberryJuice** [GTNewHorizons/Applied-Energistics-2-Unofficial#588]
AE2 version：rv3-beta-462
Using shift+cancel to mark missing items in the crafting plan of some items will steadily trigger a crash
like this：
![e0823b2b910e77bf1269492c4bc56fa1](https://github.com/user-attachments/assets/8e187279-9ebd-47e3-afda-3c4ac3f6cddb)
and it will give a crash with this：
![320d25d4b2249325bd4ff72832184989](https://github.com/user-attachments/assets/f83f9174-4d61-47c3-8fef-23da78f8e63e)

**Comment by slprime** [comment]
need more details how to reproduce this bug
