### ISSUE TITLE
Crash when using Matter Cannons from Dispensers

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/Applied-Energistics-2-Unofficial#86]
As per title.

There is a whole class dedicated to it so it leaves me scratching my head on this:
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/9b42792b3957a8886682710e180bf948c55a0ea3/src/main/java/appeng/hooks/DispenserMatterCannon.java#L67

**How to reproduce:**
-Place a charged Matter Cannon in dispenser
-Activate it with redstone.

**Crash report:**
[crash-2021-12-31_16.43.24-server.txt](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/7796697/crash-2021-12-31_16.43.24-server.txt)

**Comment by repo-alt** [comment]
Wow, looks like I'm not getting notifications from the issues on the repository.

**Comment by repo-alt** [comment]
Well, it was trying to tell the fake player that it is out of ammo. Bad idea.
